### ISSUE TITLE
gspreadsheets. Update component to new sailor version / use new logger functionality / dockerize

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/gspreadsheets#20]
**DoD**
**Development:**
- [x] use new logger
- [x] component should be dockerised, add: "buildType":"docker" line into component.json
- [x] sailor version is changed from 2.4.0 to 2.5.4
- [x] CHANGELOG.md is updated
**QA:**
- [x] Smoke test is finished
- [ ] Regression testing is finished (optional)
- [ ] Support is asked to deploy to the production stage (app.elastic.io) and/or another required stage
- [ ] Component is actually deployed to the production stage (app.elastic.io) and/or another required stage
- [ ] Smoke after deploying to the production stage

**Comment by stas-fomenko** [comment]
**Smoke test checklist**
- [ ] Push to platform
- [ ] Retrieve sample
- [ ] Retrieve sample on LA (if possible)
- [ ] Run keen flow
- [ ] Run realtime flow
- [ ] Create valid creds in the flow
- [ ] Create valid creds in credentials itself
