### ISSUE TITLE
Create/Add spreadsheet row: Use dynamic created fields based on sheets schema

### ISSUE THREAD

**Issue by juhrmacher** [elasticio/gspreadsheets#24]
As a user I don't want to define a JSON formatted array to create a new row.
Insetead I expect that the component shows me all defined fields based on the speadsheet schema.

**Comment by zubairov** [comment]
Description of the actions would be also good:

![image](https://user-images.githubusercontent.com/56208/82909582-bf6a0400-9f69-11ea-9ea0-77371291b226.png)

**Comment by jhorbulyk** [comment]
@zubairov Descriptions are present: https://github.com/elasticio/gspreadsheets/blob/master/component.json#L109 however they have not been migrated to the new, backwards incompatible format that was [introduced by the platform team in release 20.15](https://docs.elastic.io/releases/2020-04-09.html#help-links-for-components)

**Comment by zubairov** [comment]
Thanks for your comment @jhorbulyk now I know who is guilty in the state of now. I hope we still could fix it :)
