### ISSUE TITLE
Create a new connector for Google Sheet API Version 4

### ISSUE THREAD

**Issue by juhrmacher** [elasticio/gspreadsheets#3]
Create a new connector for API V4
- Create Spreadsheet
- Write Data
- Read Data
- Update Spreadsheet

Examples of how to use API can be found at the following URL:
https://developers.google.com/sheets/api/quickstart/nodejs

**Comment by zubairov** [comment]
I would not prioritize `Create Spreadsheet` use-case as IMHO the most frequently spreadsheets will be created by user outside of e.io flow. As well as formatting use-cases won't be IMO the first priority for the integration users.

Important aspects of the functionality would be to:

- [ ] Work with multiple sheets in one spreadsheet
- [ ] React on changes of the spreadsheets
- [ ] Work with row-based and column-based dimensions

Good starting point could be to check [other implementations](https://zapier.com/apps/google-sheets/help)

**Comment by juhrmacher** [comment]
create spreadsheet :)

const resource = {
  properties: {
    title,
  },
};
this.sheetsService.spreadsheets.create({
  resource,
  fields: 'spreadsheetId',
}, (err, spreadsheet) =>{
  if (err) {
    // Handle error.
    console.log(err);
  } else {
    console.log(`Spreadsheet ID: ${spreadsheet.spreadsheetId}`);
  }
});

But OK, maybe you are right :)

**Comment by A3a3e1** [comment]
Tasks to finish:
* Check if new sailor logger is being used where possible
* Check whether or not any additional manipulations should be done by the end-user because of the new credentials configurations
* Do QA process

**Comment by zubairov** [comment]
@A3a3e1 could you please also plan time for this:

https://elasticio.slack.com/archives/C7D5W1ZK7/p1561452913144000?thread_ts=1561403011.142000&cid=C7D5W1ZK7

**Comment by A3a3e1** [comment]
@zubairov Already included this into the estimation 👍
