### ISSUE TITLE
Release the component version `1.1.0`

### ISSUE THREAD

**Issue by A3a3e1** [elasticio/gspreadsheets#5]
- Check if new sailor logger is being used where possible
- Check whether or not any additional manipulations should be done by the end-user because of the new credentials configurations
- Do QA process

**Comment by juhrmacher** [comment]
Do not deploy until:

"Check whether or not any additional manipulations should be done by the end-user because of the new credentials configurations"

is fully examinated

**Comment by A3a3e1** [comment]
Duplicate of https://github.com/elasticio/gspreadsheets/issues/3
