### ISSUE TITLE
Add OIH Action: Read sheet

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/gspreadsheets#63]
# New OIH Action: Read sheet
*Modification of Lookup Objects (Plural)*

## Config Fields
* Spreadsheet (Dynamic dropdown, required): Same as other actions & triggers
* Dimension (Static dropdown, required):
* Use first row or column as a header (Static dropdown, required): Same as other actions & triggers
* Emit Behavior (Static dropdown `Emit All` or `Emit Individually`, required): 

## Input Metadata
* Worksheet (String enum, required): Worksheet to read

## Output Metadata
The rows/columns on the sheet

**Comment by A3a3e1** [comment]
@jhorbulyk Should 'worksheet' be in the input metadata or in the config as in the other actions?

**Comment by jhorbulyk** [comment]
> Should 'worksheet' be in the input metadata or in the config as in the other actions?

It could be in the config section (as in other actions). The argument for putting it as a message input is that it doesn't alter the other inputs. However, if there is a difference between the system representation for a worksheet vs what the user sees, then we should keep the option in the config.
