### ISSUE TITLE
Record a video for verification on Google's platform

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/gspreadsheets#8]
We should record and provide a video description with overview of the component's functionality. in order to get a permission for retrieving metadata information on Google Spreadsheet's platform.

**Comment by zubairov** [comment]
@kirill-levitskiy could you please document in this issue all information we've sent to Google (list of permissions, description etc.) as well as link to the youtube video. Our WL customers would have to do the same so it will be very useful for them too.

@khanzadyan cc
