### ISSUE TITLE
Component can not retrieve image from sheet

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/gspreadsheets#9]
**Description:** 
The component does not retrieve a cell with an image

**STR**
1. Create new test google sheet and insert an image into at least one cell:
![image](https://user-images.githubusercontent.com/36419533/60713450-d226b500-9f21-11e9-9a50-59ef1b27cd47.png)
2. Create new flow and select gspreadsheets: New Spreadsheet Row Trigger as the First step 
3. Input for the First step:
**Spreadsheet** - select a proper one
**Worksheet** - select a proper one
**Dimension** - ROWS
**Use first row/column as a header** - Yes
**Select All Data** - Yes
4. Retrieve sample.

**AR:** 
1. Sample retrieved with no image
2. A column with the image is not shown in the sample
```
{
  "HEADER5": "1",
  "HEADER4": "yyy",
  "HEADER3": "qwer",
  "HEADER2": "w",
  "HEADER1": "q"
}
```

**ER:**
ER depends on the investigation results:
- In sample retrieved shown some info that there is an image 
- image retrieved

**Comment by juhrmacher** [comment]
https://stackoverflow.com/questions/39489282/retrieve-images-in-cells-using-google-sheets-api

**Comment by zubairov** [comment]
I didn't actually know that you could store binary data in cells. Not sure it's a widely used feature tbh :)

**Comment by uaArsen** [comment]
Investigation results:

**Comment by zubairov** [comment]
interesting results @uaArsen thanks for sharing it. Does it mean that if value of the cell `39482,2345` and it's formatted as money, like this:

![image](https://user-images.githubusercontent.com/56208/61300031-81e10a00-a7e1-11e9-89fd-9fef5fc2e1cb.png)

in elastic.io flow we will get  a string with the `€` sign in it and not the original number?

@stas-fomenko did we tested it?

**Comment by juhrmacher** [comment]
I just had a short conversation about this with @zubairov about this. We both think that we should not include this parameter in our component. @zubairov right?

**Comment by juhrmacher** [comment]
OK conclusion: We will not implement this feature. The issue can be closed.
A new issue needs to be created to use the option UNFORMATTED_VALUE as default.

**Comment by stas-fomenko** [comment]
@zubairov no, but it seems to me as correct behavior. 
also, we did not get requirements that cell formatting must be ignored in read action

**Comment by uaArsen** [comment]
@zubairov Just tested behavior existing component will retrieve value 39.482,23 . If value is set to `FORMULA` it will retrieve unformatted value 39482,23

**Comment by zubairov** [comment]
@stas-fomenko 

> also, we did not get requirements that cell formatting must be ignored in read action

Sure, I was not criticizing, thanks to @uaArsen we know more now so can formulate a new enhancement request :)

> @zubairov Just tested behavior existing component will retrieve value 39.482,23 € . If value is set to FORMULA it will retrieve unformatted value 39482,2345

@uaArsen, thank for confirming it, however UNFORMATTED_VALUE is more benefitial, otherwise we could get something like `=SUM(A1;A23)` which is absolutely of no use for the user of elastic.io platform :)

I'll create a new enhancement request to use `UNFORMATTED_VALUE`.

**Comment by stas-fomenko** [comment]
closed according to the discussion in the current thread
